name: Deploy Astro site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "."

jobs:
  build:
    name: Build Astro Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Detect Package Manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
            echo "manager=pnpm" >> $GITHUB_ENV
            echo "install_cmd=install --frozen-lockfile" >> $GITHUB_ENV
            echo "run_cmd=pnpm exec" >> $GITHUB_ENV
            echo "lockfile=pnpm-lock.yaml" >> $GITHUB_ENV
          elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_ENV
            echo "install_cmd=install --frozen-lockfile" >> $GITHUB_ENV
            echo "run_cmd=yarn run" >> $GITHUB_ENV
            echo "lockfile=yarn.lock" >> $GITHUB_ENV
          elif [ -f "${{ github.workspace }}/package-lock.json" ]; then
            echo "manager=npm" >> $GITHUB_ENV
            echo "install_cmd=ci" >> $GITHUB_ENV
            echo "run_cmd=npx --no-install" >> $GITHUB_ENV
            echo "lockfile=package-lock.json" >> $GITHUB_ENV
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ env.manager }}
          cache-dependency-path: ${{ env.BUILD_PATH }}/${{ env.lockfile }}

      # 🔥 Explicitly Install `pnpm` if needed
      - name: Install pnpm (if required)
        if: env.manager == 'pnpm'
        run: |
          corepack enable
          npm install -g pnpm
          pnpm --version  # Check if pnpm is installed

      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Dependencies
        run: ${{ env.manager }} ${{ env.install_cmd }}
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build Astro Site
        run: |
          ${{ env.run_cmd }} astro build \
            --site "${{ steps.pages.outputs.origin }}" \
            --base "${{ steps.pages.outputs.base_path }}"
        working-directory: ${{ env.BUILD_PATH }}

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Site
        id: deployment
        uses: actions/deploy-pages@v4
